#!/bin/bash
version=`python3 -c "import electrum_ptc; print(electrum_ptc.version.ELECTRUM_VERSION)"`
sig=`./run_electrum_ptc -w $SIGNING_WALLET signmessage $SIGNING_ADDRESS $version`
echo "{ \"version\":\"$version\", \"signatures\":{ \"$SIGNING_ADDRESS\":\"$sig\"}}"
